USE Calendario;
#DROP DATABASE CALENDARIO;


# CPFs validos (apenas criar usuários com os cpfs incluídos aqui)

INSERT INTO TIPO_USUARIO VALUES('1', 1);
INSERT INTO TIPO_USUARIO VALUES('2', 2);
INSERT INTO TIPO_USUARIO VALUES('3', 2);
INSERT INTO TIPO_USUARIO VALUES('4',1);
INSERT INTO TIPO_USUARIO VALUES('5', 1);

# Usuarios teste

INSERT INTO USUARIO VALUES('a@a.a', 'b', 'c', 'Fulano', 'da Silva', '2021-03-30 00:00:00', 1, 1); #aluno
INSERT INTO USUARIO VALUES('b@b.b', 'c', 'd', 'Ciclano', 'Lima', '2021-03-30 00:00:00', 2, 2); #professor
INSERT INTO USUARIO VALUES('josevaldocristao@gmail.com', 'admin', '123', 'Josevaldo', 'Cristão', '2021-03-30 00:00:00', 3, 3);

# Turmas teste

INSERT INTO TURMA VALUES('3INFO');
INSERT INTO TURMA VALUES('3ENF');
INSERT INTO TURMA VALUES('3AUTO');
INSERT INTO TURMA VALUES('2INFO');
INSERT INTO TURMA VALUES('2ENF');
INSERT INTO TURMA VALUES('2AUTO');
INSERT INTO TURMA VALUES('1INFO');
INSERT INTO TURMA VALUES('1ENF');
INSERT INTO TURMA VALUES('1AUTO');

# Matriculas

INSERT INTO MATRICULA_TURMA VALUES(NULL, '3INFO', '1');
INSERT INTO MATRICULA_TURMA VALUES(NULL, '3INFO', '2');
INSERT INTO MATRICULA_TURMA VALUES(NULL, '2INFO', '2');
INSERT INTO MATRICULA_TURMA VALUES(NULL, '1INFO', '2');
INSERT INTO MATRICULA_TURMA VALUES(NULL, '2INFO', '3');
INSERT INTO MATRICULA_TURMA VALUES(NULL, '3INFO', '3');

# Disciplinas teste

INSERT INTO DISCIPLINA VALUES('ARQ', 'Arquitetura de computadores', '2');
INSERT INTO DISCIPLINA VALUES('SO', 'Arquitetura de sistemas operacionais', '2');
INSERT INTO DISCIPLINA VALUES('BIO1', 'Biologia 1º ano', '3');
INSERT INTO DISCIPLINA VALUES('BIO2', 'Biologia 2º ano', '3');

# Matriculas

INSERT INTO MATRICULA_DISCIPLINA VALUES(NULL, '1', 'ARQ');
INSERT INTO MATRICULA_DISCIPLINA VALUES(NULL, '2', 'ARQ');
INSERT INTO MATRICULA_DISCIPLINA VALUES(NULL, '2', 'SO');
INSERT INTO MATRICULA_DISCIPLINA VALUES(NULL, '1', 'BIO1');
INSERT INTO MATRICULA_DISCIPLINA VALUES(NULL, '3', 'BIO1');
INSERT INTO MATRICULA_DISCIPLINA VALUES(NULL, '3', 'BIO2');

# Selects

select * from usuario;
select * from turma;
select * from matricula_turma;
select * from disciplina;
select * from matricula_disciplina;
select * from atividade;

select * from usuario, tipo_usuario where usuario.cpf = tipo_usuario.cpf;
select * from atividade_turma;
select * from atividade_disciplina;

SELECT count(DISTINCT ID) as COUNT FROM TURMA WHERE ID IN('1info', '2info', 'tur3');
SELECT count(DISTINCT ID) as COUNT FROM TURMA WHERE ID IN('1info', '2info', '3enf');
SELECT count(DISTINCT ID) as COUNT, count(DISTINCT ID) as COUNT2 FROM TURMA WHERE ID IN('1info', '2info', '3enf');

CREATE VIEW ATIVIDADES_DA_DISCIPLINA AS SELECT TITULO, DESCRICAO, ATIVIDADE.ID, DISCIPLINA FROM ATIVIDADE, ATIVIDADE_DISCIPLINA WHERE ATIVIDADE.ID = ATIVIDADE_DISCIPLINA.ATIVIDADE;
CREATE VIEW ATIVIDADES_DA_TURMA AS SELECT TITULO, DESCRICAO, ATIVIDADE.ID, TURMA FROM ATIVIDADE, ATIVIDADE_TURMA WHERE ATIVIDADE.ID = ATIVIDADE_TURMA.ATIVIDADE;

SELECT DISTINCT * FROM ATIVIDADES_DA_TURMA INNER JOIN MATRICULA_TURMA ON MATRICULA_TURMA.TURMA = ATIVIDADES_DA_TURMA.TURMA WHERE USUARIO="2";
SELECT * FROM ATIVIDADES_DA_DISCIPLINA;

SELECT * FROM ATIVIDADES_DA_TURMA INNER JOIN MATRICULA_TURMA ON ATIVIDADES_DA_TURMA.TURMA = MATRICULA_TURMA.TURMA;

#DROP VIEW ATIVIDADES_DA_TURMA;
#DROP VIEW ATIVIDADES_DA_DISCIPLINA;
